image: ghcr.io/vvv-school/gitpod:latest
ports:
- port: 6080
  onOpen: notify
- port: 10000-20000
  onOpen: ignore
workspaceLocation: "."
tasks:
- init: init-icubcontrib.sh
- command: start-vnc-session.sh
- command: gp ports await 6080 && gp preview $(gp url 6080)
- command: git clone https://github.com/ttk592/spline.git /workspace/spline
